apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: delete-method
route:
  methods:
    - delete
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: get-method
route:
  methods:
    - get
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: post-method
route:
  methods:
    - post
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-key-auth-m0
plugin: key-auth
config:
  key_names:
    - api_key
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-key-auth-m1
plugin: key-auth
config:
  key_names:
    - api_key
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-0
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-1
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet/findByStatus
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-2
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet/findByTags
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-3
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: delete-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-4
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: add-key-auth-m0
    konghq.com/override: get-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-5
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: post-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-6
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /pet/.*/uploadImage
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-7
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: add-key-auth-m1
    konghq.com/override: get-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /store/inventory
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-8
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /store/order
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-9
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /store/order/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-10
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /user
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-11
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /user/createWithArray
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-12
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /user/createWithList
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-13
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /user/login
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-14
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /user/logout
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-15
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-0
                port:
                  number: 80
            path: /user/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-16
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-17
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet/findByStatus
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-18
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet/findByTags
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-19
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: delete-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-20
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: add-key-auth-m0
    konghq.com/override: get-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-21
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: post-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-22
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /pet/.*/uploadImage
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-23
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: add-key-auth-m1
    konghq.com/override: get-method
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /store/inventory
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-24
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /store/order
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-25
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /store/order/.*
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-26
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /user
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-27
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /user/createWithArray
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-28
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /user/createWithList
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-29
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /user/login
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-30
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /user/logout
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petstore-31
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: petstore.swagger.io
      http:
        paths:
          - backend:
              service:
                name: petstore-service-1
                port:
                  number: 80
            path: /user/.*
            pathType: ImplementationSpecific

